theme: jekyll-theme-cayman
title: Il Valore degli Open Data
description: Parliamo delle elezioni comunali del 2016 per capire cosa sono e a cosa servono
show_downloads: "true"
google_analytics: "G-66WJMS2LLL"
