theme: jekyll-theme-cayman
title: Il Valore degli Open Data
email: mirkotritella1999@gmail.com
github_username: Emeierkeio
description: I dati delle elezioni comunali rosetane del 2016 da un nuovo punto di vista
show_downloads: "true"
google_analytics: "G-66WJMS2LLL"
