theme: jekyll-theme-cayman
title: I dati delle elezioni comunali rosetane del 2016 da un nuovo punto di vista
description: Il Ruolo degli Open Data nell'informazione pubblica
show_downloads: "true"
google_analytics: "G-66WJMS2LLL"
